### ISSUE TITLE
Lock file support

### ISSUE THREAD

**Issue by SpEcHiDe** [MTKruto/MTKruto#152]
https://github.com/MTKruto/MTKruto/blob/3cb416e4e48b374d9d974cf5d8a3dfda6cbb28b3/0_deps.ts#L21

**Comment by roj1512** [comment]
Lock files are still not properly supported

![image](https://github.com/MTKruto/MTKruto/assets/49933115/a0b42fd2-affe-4013-96a4-84ab0af02831)

**Comment by roj1512** [comment]
Fixed since https://github.com/MTKruto/debug/commit/237b636895cf7a1b0d13c4ed17b26ef1d17b5f01.
