### ISSUE TITLE
Fetch access hash if necessary (automatically or manually)

### ISSUE THREAD

**Issue by baumschubser** [MTKruto/MTKruto#236]
Hi there, excellent work, I am migrating from gram.js and it is nice to see the little things that make this lib fun to work with. Congratulations to it (also the JSON server is really great, even with a little preact-dashboard).

My question: I want to access a channel (`client.getChat(id)`) directly, without calling `client.getChats` first. That fails because I don't have the access hash yet.

I want to minimize API calls, so what can I do to fetch that access hash, if it is not yet cached? What I want is "get chat (or forum topic etc.), fetch access hash before if necessary".

Would this be feasible to include in the lib to do it automatically?

Thanks for the great work!

**Comment by rojvv** [comment]
Do you want to minimize API calls on the higher-level as in you sending less requests to MTKruto Server or on the lower-level as in MTKruto Server sending less requests to Telegram? If the latter, it is impossible. If the former, I don't have a strong reason to implement it yet.

**Comment by baumschubser** [comment]
The latter, minimizing API calls to Telegram.

So my only way to make sure `getChat` works is to call `client.getChats` before?

**Comment by rojvv** [comment]
> So my only way to make sure `getChat` works is to call `client.getChats` before?

For users, yes.

**Comment by nxtgencat** [comment]
> Hi there, excellent work, I am migrating from gram.js and it is nice to see the little things that make this lib fun to work with. Congratulations to it (also the JSON server is really great, even with a little preact-dashboard).
> 
> My question: I want to access a channel (`client.getChat(id)`) directly, without calling `client.getChats` first. That fails because I don't have the access hash yet.
> 
> I want to minimize API calls, so what can I do to fetch that access hash, if it is not yet cached? What I want is "get chat (or forum topic etc.), fetch access hash before if necessary".
> 
> Would this be feasible to include in the lib to do it automatically?
> 
> Thanks for the great work!

I’m new to using this library and trying to send a message to a private channel, but I keep getting the error: AccessError: Cannot access the chat because there is no access hash for it.

Could you please provide a sample snippet or guide me on how to fetch the access hash and send the message? Thanks!
