### ISSUE TITLE
Test DC: Cannot authenticate

### ISSUE THREAD

**Issue by baumschubser** [MTKruto/MTKruto#244]
The following code works with prod DC (`setDc('2')`), but not with test DC (`setDc('2-test')`).

With test DC, the code is prompted again and again. When I hardcode it (five times "2", [as specified](https://core.telegram.org/api/auth)), I get a FLOOD_WAIT error).

```
const client = new Client({
  apiId: 123456789,
  apiHash: "aaaaafffffeeeee",
});
await client.setDc('2');
await client.start({
  phone: '+491782869656',
  code: () => prompt('Code')!,
  password: () => prompt("Enter your account's password:")!,
});
console.log("Started.");
```

**Comment by rojvv** [comment]
This has to do how Telegram behaves. Real numbers of some countries aren't even supported on test servers, so that could be a reason.

Closing this as it is not something MTKruto can fix.
